version: '3.7'

services: 
  php:
    build:
      context: ../
      dockerfile: dev.Dockerfile
    environment:
        MYSQL_USER: 'mysql'
        MYSQL_PASSWORD: 'mysql'
        MYSQL_DATABASE: 'mysql'
        IS_DEV: 'true'
  mysql:
    image: mysql:8
    volumes:
        - mysqldata:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 'mysql'
        MYSQL_USER: 'mysql'
        MYSQL_PASSWORD: 'mysql'
        MYSQL_DATABASE: 'mysql'

volumes:
  mysqldata: {}
