version: '3.7'

services: 
  php:
    build:
      context: ../
      dockerfile: dev.Dockerfile
    environment:
        MYSQL_USER: 'mysql'
        MYSQL_PASSWORD: 'mysql'
        MYSQL_DATABASE: 'mysql'
        IS_DEV: 'true'
  mysql:
    environment:
        MYSQL_ROOT_PASSWORD: 'mysql'
        MYSQL_USER: 'mysql'
        MYSQL_PASSWORD: 'mysql'
        MYSQL_DATABASE: 'mysql'

volumes:
  mysqldata: {}
